### ISSUE TITLE
Font inconsistency

### ISSUE THREAD

**Issue by cmanszew** [ArturB/WUT-Thesis#34]
According to Ms. Wiesława Duszyńska, the correct font is Times New Roman. Also, there is a claim, that the font type is inconsistent, although I can't see it.

**Comment by kekore** [comment]
Yep. In my case she claimed that font in list of content is smaller than the rest also.

**Comment by ArturB** [comment]
Current template was agreed with Ms. Duszyńska in May and she has no compaints about the font. 
Font is somewhat smaller in table of contents, that's true, and it was OK then. 
Maybe I'll write an email to her with some questions.

**Comment by cmanszew** [comment]
> and she has no compaints about the font.

Unfortunately, that is not what I heard. She was complaining about the fonts and said that she told "that student" so many times, and he didn't listen. Nevertheless, the template is great and I really appreciate it. I guess that even when one gets everything right, she'll make up something, just to have a reason to complain.

**Comment by marcullo** [comment]
I also had some complications talking about the font but actually it turned out just to be something like it just should either be (excluding title page and listings hopefully):
- one font in the whole document (also in authorship which is risky to do I guess) or
- original authorship and the rest in one other font

and I heard also that yeah we could simplify thesis to have the same font size everywhere (starting with table of contents and excluding headers, footers and headers of sections).

**Comment by kekore** [comment]
I heard the first page should be also with same font as the rest. Authorship page should stay as original.

**Comment by ArturB** [comment]
>     one font in the whole document (also in authorship which is risky to do I guess)
It's not "risky", it's impossible because authorship page is inserted as image, downloaded from Faculty's webpage. It's known to Ms. Duszyńksa from the very beginning.

**Comment by kekore** [comment]
> > ```
> > Authorship page should stay as original
> > ```
> 
> authorship page was changed upon request of dyr. Kożuszek, because original PDF was in small resolution, and I agree here with dyr. Kożuszek.

You misunderstood me. I meant I was told the page with authorship is all right as is now in response to @marcullo who said the font there should be changed. I didn't mean the very original document.

**Comment by ArturB** [comment]
> Szanowny Panie,
> Nie zgłaszałam wcześniej kroju i wielkości czcionki, bo problem pojawił się dopiero teraz przy przynoszeniu przez studentów wzorcowych stron pracy dyplomowej.
> Studenci przynoszą mi strony wzorcowe z różnym krojem i wielkością czcionki i myślę, że to nie Pana wina. Podkreślam, że żadnej pracy nie odrzuciłam - nawet przyjęłam dwie, gdzie czcionki różniły się - mimo, że termin składania prac inżynierskich jest 3.02.br., a prac magisterskich 14.02.br. Co do deklaracji nie miałam zastrzeżeń. O ile sobie przypominam to jeden student miał bardzo malutkim fontem deklarację - to mogłam coś na ten temat powiedzieć. [...] Mam nadzieję, że już nie będzie problemów.
> Z poważaniem,
> Wiesława Duszyńska

In [Releases](https://github.com/ArturB/WUT-Thesis/releases) you can find version 2.1.2, with font in Table of Contents, List of Figures, in figures captions etc. the same size as in the main text. When it comes to font type, it remains the same as now. Ms. Duszyńska shouldn't make more complaints about it. 

I'll publish new version on Overleaf as soon as Overleaf employees will accept the changes. And also please always check your thesis two times before giving it to Ms. Duszyńska, because maybe you did some unintentional changes in font in some place, and I'll argue about her complaints without reason.
